//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonTranslator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonTranslator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentralServer.Resources.CommonTranslator", typeof(CommonTranslator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускается однократно {0}.
        /// </summary>
        internal static string AtDate {
            get {
                return ResourceManager.GetString("AtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить корзину.
        /// </summary>
        internal static string CleanRecycleBin {
            get {
                return ResourceManager.GetString("CleanRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить временные файлы.
        /// </summary>
        internal static string CleanTmpFiles {
            get {
                return ResourceManager.GetString("CleanTmpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускается раз в месяц {0} числа в {1}.
        /// </summary>
        internal static string DayInMonth {
            get {
                return ResourceManager.GetString("DayInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускается раз в неделю в {0} в {1}.
        /// </summary>
        internal static string DayInWeek {
            get {
                return ResourceManager.GetString("DayInWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить файлы загрузки Program Files.
        /// </summary>
        internal static string RemoveDownloadedProgramFiles {
            get {
                return ResourceManager.GetString("RemoveDownloadedProgramFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить старые файлы программы CheckDisk.
        /// </summary>
        internal static string RemoveOldChkdskFiles {
            get {
                return ResourceManager.GetString("RemoveOldChkdskFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить файлы дампа памяти для системных ошибок.
        /// </summary>
        internal static string RemoveSystemErrorMemoryDumpFiles {
            get {
                return ResourceManager.GetString("RemoveSystemErrorMemoryDumpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить временные файлы инсталляций.
        /// </summary>
        internal static string RemoveTemporaryInstallationFiles {
            get {
                return ResourceManager.GetString("RemoveTemporaryInstallationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить временные файлы Интернета.
        /// </summary>
        internal static string RemoveTemporaryInternetFiles {
            get {
                return ResourceManager.GetString("RemoveTemporaryInternetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить временные файлы инсталлятора Windows.
        /// </summary>
        internal static string RemoveTemporaryWindowsInstallerFiles {
            get {
                return ResourceManager.GetString("RemoveTemporaryWindowsInstallerFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить эскизы.
        /// </summary>
        internal static string RemoveThumbnails {
            get {
                return ResourceManager.GetString("RemoveThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить лог-файл обновлений Windows.
        /// </summary>
        internal static string RemoveWindowsUpdateLogFile {
            get {
                return ResourceManager.GetString("RemoveWindowsUpdateLogFile", resourceCulture);
            }
        }
    }
}
